export const SET_USER = 'SET_USER';

export const SET_AUTH_DISPLAY = 'SET_AUTH_DISPLAY';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const POPULATE_SEARCH_RESULTS = 'POPULATE_SEARCH_RESULTS';
export const POPULATE_TOP_FOUR = 'POPULATE_TOP_FOUR';
