export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const TOGGLE_AUTH_DISPLAY = 'TOGGLE_AUTH_DISPLAY';
export const TOGGLE_IS_LOGGED_IN = 'TOGGLE_IS_LOGGED_IN';
export const POPULATE_SEARCH_RESULTS = 'POPULATE_SEARCH_RESULTS';
export const POPULATE_TOP_FOUR = 'POPULATE_TOP_FOUR';
